config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/about',	to: 'static_pages#about',   via: 'get'

  resources :users
  match '/signup',	to: 'users#new',   			via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',	to: 'sessions#new',			via: 'get'
  match '/signout', to: 'sessions#destroy',		via: 'delete'

  resources :answers do
	  resources :questions, only: [:create, :edit, :update, :destroy]
	end

  match '/votes/:type/:id/:vote',    to: 'votes#vote',     via: 'post',   as: 'vote'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	acts_as_votable #voting
	
	#associations
	belongs_to :user
	has_many :questions

	validates :title, presence: true, length: { maximum: 255 }
	validates :content, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
	acts_as_votable #voting

	#associations
	belongs_to :user
	belongs_to :answer

	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_voter #voting

	# associations
	has_many :answers
	has_many :questions

	# Save a downcased version of the username for login
	before_save { self.username = username.downcase }
	before_create :create_remember_token

	validates(:username, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false } )

	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]

	def new
		@answer = Answer.new
	end

	def create
		@user = current_user
		@answer = @user.answers.new(answer_params)
		if @answer.save
			flash[:success] = "Answer \'#{answer_params[:title]}\' successfully posted!"
			redirect_to @answer
		else
			render 'new'
		end
	end

	def edit
		@answer = Answer.find(params[:id])
	end

	def update
		@answer = Answer.find(params[:id])
		render 'edit' unless current_user.admin? || current_user?(@answer.user)
		if @answer.update_attributes(answer_params)
			flash[:success] = "\'#{@answer.title}\' successfully updated!"
			redirect_to @answer
		else
			render 'edit'
		end
	end

	def index
		@answers = Answer.paginate(page: params[:page]).order(updated_at: :desc)
	end

	def show
		@answer = Answer.includes(:user, questions: :user).find(params[:id])
	end

	def destroy
		answer = Answer.find(params[:id])
		if current_user.admin? || current_user?(answer.user)
			answer.destroy
			flash[:success] = "\'#{answer.title}\' was successfully deleted."
			redirect_to answer.user
		else
			flash[:danger] = 'No permission to delete'
			redirect_to answers_path
		end
	end

	private
		def answer_params
			params.require(:answer).permit(:title, :content)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :signed_in_user, only: [:create, :edit, :update, :destroy]

	def create
		@answer = Answer.find(params[:answer_id])
		@question = @answer.questions.new(question_params)
		@question.user_id = current_user.id
		if @question.save
			flash[:success] = "Question Saved"
			redirect_to @answer
		else
			render 'answers/show'
		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		question = Question.find(params[:id])
		render :edit unless current_user.admin? || current_user?(@question.user)
		if question.update_attributes(question_params)
			flash[:success] = 'Question updated!'
			redirect_to question.answer
		else
			render :edit
		end
	end

	def destroy
		question = Question.find(params[:id])
		if current_user.admin? || current_user?(@question.user)
			question.destroy
			flash[:success] = 'Question destroyed!'
			redirect_to question.answer
		else
			flash[:danger] = 'No permission to delete'
			redirect_to question.answer
		end
	end

	private
		def question_params
			params.require(:question).permit(:content)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
	    user = User.find_by(username: params[:session][:username].downcase)
	    if user && user.authenticate(params[:session][:password])
	      sign_in user
	      redirect_back_or user
	    else
	      flash.now[:error] = 'Invalid username/password combination'
	      render 'new'
	    end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update, :index, :show, :destroy]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: :destroy

	def show
		@user = User.includes(:answers).find(params[:id])
	end

	def index
		@users = User.paginate(page: params[:page])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Questionit!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(settings_params)
			flash[:success] = "Profile Updated!"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		user = User.find(params[:id]).destroy
		flash[:success] = "#{user.id} #{user.name} deleted with username: #{user.username}"
		redirect_to users_url
	end

	private

		def user_params
			params.require(:user).permit(:username, :name, :password, :password_confirmation)
		end

		def settings_params
			params.require(:user).permit(:name, :password, :password_confirmation)
		end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def vote
		if params[:type] == 'answer'
			if params[:vote] == 'like'
				current_user.likes Answer.find(params[:id])
			elsif params[:vote] == 'dislike'
				current_user.dislikes Answer.find(params[:id])
			end
		elsif params[:type] == 'question'
			if params[:vote] == 'like'
				current_user.likes Question.find(params[:id])
			elsif params[:vote] == 'dislike'
				current_user.dislikes Question.find(params[:id])
			end
		end
		redirect_to answer_path(id: params[:id])
	end

	def unvote
		if params[:type] == 'answer'
			current_user.unvote_for Answer.find(params[:id])
		elsif params[:type] == 'question'
			current_user.unvote_for Question.find(params[:id])
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Questionit"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		# Creates a cookie that expires 20.years.from_now
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user	
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			flash[:danger] = 'Please sign in'
			redirect_to signin_url
		end
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/edit.html.slim
- provide(:title, 'Edit Answer')
h1 Edit

= form_for @answer do |f|

  .form-group
    = f.label :title, class: 'control-label'
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :content, class: 'control-label'
    = f.text_area :content, class: 'form-control', rows: '3'

  = f.submit "Save Changes", class: "btn btn-large btn-primary"
	

app/views/answers/index.html.slim
- provide(:title, 'Answers')
h1.center Answers

= will_paginate renderer: BootstrapPagination::Rails
= link_to 'New Answer', new_answer_path, class: 'btn btn-primary new-answer-btn'

ul.list-group
	- @answers.each do |answer|
		li.list-group-item
			span.badge = answer.weighted_score
			h4
				= link_to answer.title, answer_path(answer)
				|  (
				= pluralize(answer.questions.count, 'question')
				| )
			= answer.content
			- if signed_in? && current_user.admin?
				br
				.btn-group
					= link_to 'Edit', edit_answer_path(answer), class: 'btn btn-success btn-xs'
					= link_to 'Delete', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'

= will_paginate renderer: BootstrapPagination::Rails

app/views/answers/new.html.slim
- provide(:title, 'New Answer')
h1 New Answer
= form_for @answer do |f|
	
	.form-group
		= f.label :title, class: 'control-label'
		= f.text_field :title, class: 'form-control', placeholder: 'Title'

	.form-group
		= f.label :content, class: 'control-label'
		= f.text_area :content, class: 'form-control', placeholder: 'Enter answer', rows: '3'

	= f.submit 'Post Answer', class: 'btn btn-primary btn-lg'

app/views/answers/show.html.slim
- provide(:title, @answer.title)

h3 = @answer.title
hr

.row
	.col-md-10
		.col-xs-1
			.btn-group
				= link_to 'like', vote_path(type: 'answer', id: @answer.id, vote: 'like'), method: :post, class: 'btn btn-success btn-xs'
				= link_to 'dislike', vote_path(type: 'answer', id: @answer.id, vote: 'dislike'), method: :post, class: 'btn btn-danger btn-xs'
		.col-xs-11
			= @answer.content
			.text-right
				| Posted by 
				= @answer.user.name
				|  (
				= link_to @answer.user.username, user_path(@answer.user)
				| )
			.text-right
				.btn-group
					= link_to 'Edit', edit_answer_path(@answer), class: 'btn btn-success btn-xs'
					= link_to 'Delete', answer_path(@answer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'
	.col-md-2
		= @answer.created_at.strftime("answered %F")
hr

.col-md-10
	- @answer.questions.each do |question|
		.row
			.col-xs-1
				p.text-justify add vote button here
			.col-xs-11
				= question.content
				.text-right
					| Posted by 
					= question.user.name
					|  (
					= link_to question.user.username, user_path(question.user)
					| )
				.text-right
					.btn-group
						= link_to 'Edit', edit_answer_question_path(answer_id: @answer.id, id: question.id), class: 'btn btn-success btn-xs'
						= link_to 'Delete', answer_question_path(answer_id: @answer.id, id: question.id), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs'
		hr
	.row
		= form_for [@answer, Question.new] do |f|
			.form-group
				= f.label :'New Question', class: 'control-label'
				= f.text_area :content, class: 'form-control', placeholder: 'Enter question', rows: '3'
	
			= f.submit 'Post Question', class: 'btn btn-primary btn-md'

.col-md-2
	h3 similar

app/views/layouts/_footer.html.slim
footer
	.container
		small
			= link_to 'placeholder', '#'
		nav
			ul
				li = link_to 'About', about_path
				li = link_to 'placeholder', '#'

app/views/layouts/_header.html.slim
header
	nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse role="navigation"
		.container.fluid
			.navbar-header
				= link_to 'QuestionIt', root_path, class: "navbar-brand"
				button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1'
					span.sr-only Toggle navigation
					span.icon-bar
					span.icon-bar
					span.icon-bar

			.collapse.navbar-collapse#bs-example-navbar-collapse-1
				ul.nav.navbar-nav.navbar-right
					/ Menu items that are there regardless of whether you are signed in or not
					li = link_to 'Home', root_path
					li = link_to 'Users', users_path
					li = link_to 'Answers', answers_path
					- if signed_in?
						li.dropdown
							a href='#' class='dropdown-toggle' data-toggle='dropdown'
								| Account
								span.caret
							ul.dropdown-menu role='menu'
								li = link_to 'Profile', current_user
								li = link_to 'Settings', edit_user_path(current_user)
								li.divider
								li = link_to 'Sign Out', signout_path, method: "delete"
					- else
						li = link_to 'Sign in', signin_path

app/views/layouts/application.html.slim
doctype html
head
	title == full_title(yield(:title))
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

body

	== render 'layouts/header'

	- flash.each do |key, value|
		div class="container alert alert-#{key}" = value

	.container
		== yield

	== render 'layouts/footer'

	.container
		== debug(params) if Rails.env.development?

app/views/questions/edit.html.slim
- provide(:title, "Edit question")
h1 Edit Question

= form_for [@question.answer, @question] do |f|

  .form-group
    = f.label :question
    = f.text_area :content, class: 'form-control', rows: '3'

  = f.submit "Save Changes", class: "btn btn-large btn-primary"

app/views/shared/_error_messages.html.slim
- if object.errors.any?
	div class="alert alert-danger"
		| The form contains 
		= pluralize(object.errors.count, "error")

	ul
		- object.errors.full_messages.each do |msg|
			li
				|
					* 
				= msg

app/views/static_pages/about.html.slim
.jumbotron
	h1 About

app/views/static_pages/home.html.slim
.jumbotron
	h1 QuestionIt
	p The answer and question site!
	- if signed_in?
		= link_to 'Post Answer', new_answer_path, class: 'btn btn-primary btn-lg main-btn'
		= link_to 'Question an Answer', answers_path, class: 'btn btn-primary btn-lg main-btn'
	- else
		= link_to 'Sign up', new_user_path, class: 'btn btn-primary btn-lg main-btn'
		= link_to 'Sign in', signin_path, class: 'btn btn-primary btn-lg'

app/views/users/edit.html.slim
- provide(:title, "Edit user")
h1 Update your profile

= form_for(@user) do |f|
  = render 'shared/error_messages', object: f.object

  .form-group
    = f.label :name
    = f.text_field :name

  .form-group
    = f.label :password
    = f.password_field :password

  .form-group
    = f.label :password_confirmation, "Confirm Password"
    = f.password_field :password_confirmation

  = f.submit "Save Changes", class: "btn btn-large btn-primary"

app/views/users/index.html.slim
- provide(:title, "Userlist")
h1 All Users

= will_paginate renderer: BootstrapPagination::Rails

ul.list-group
	- @users.each do |user|
		li.list-group-item
			=> user.id
			=> link_to(user.username,user)
			=> user.name
			- if current_user.admin? && !current_user?(user)
				| | 
				= link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

= will_paginate renderer: BootstrapPagination::Rails

app/views/users/new.html.slim
- provide(:title, 'Sign up')
h1.center Sign up
= form_for @user do |f|
	= render 'shared/error_messages', object: f.object

	.form-group
		= f.label :username, class: 'control-label'
		= f.text_field :username, class: 'form-control', placeholder: 'Username'

	.form-group
		= f.label :name, class: 'control-label'
		= f.text_field :name, class: 'form-control', placeholder: 'Display Name'

	.form-group
		= f.label :password, class: 'control-label'
		= f.password_field :password, class: 'form-control', placeholder: 'Password'

	.form-group
		= f.label :password_confirmation, 'Confirmation', class: 'control-label'
		= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm password'

	= f.submit 'Create Account', class: 'btn btn-primary btn-lg'

app/views/users/show.html.slim
- provide(:title, @user.username)
h1
	=> @user.name
	small = @user.username
hr

h3 My Answers
ul.list-group
- @user.answers.each do |answer|
	li.list-group-item
		span.badge = answer.weighted_score
		h4
			= link_to answer.title, answer_path(answer)
			|  (
			= pluralize(answer.questions.count, 'question')
			| )
		= answer.content
		|  
		- if current_user.admin? || current_user?(@user)
			br
			.btn-group
				= link_to 'Edit', edit_answer_path(answer), class: 'btn btn-success btn-xs'
				= link_to 'Delete', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'